-- VENDA REALIZADA DENTRO DO PERÍODO DE CAMPANHA
INSERT INTO VENDAS_ONLINE (ID_VENDA, ID_PRODUTO, ID_CLIENTE, CATEGORIA, QTD_VENDIDA, PRECO_UNITARIO, VALOR_TOTAL, DATA_VENDA, FORMA_PAGAMENTO, ORIGEM_VENDA)
VALUES 
(1, 101, 201, 'FPS', 1, 60.00, 60.00, '2025-01-15', 'Cartão de Crédito', 'E-commerce');

-- VENDA REALIZADA FORA DO PERÍODO DE CAMPANHA
INSERT INTO VENDAS_ONLINE (ID_VENDA, ID_PRODUTO, ID_CLIENTE, CATEGORIA, QTD_VENDIDA, PRECO_UNITARIO, VALOR_TOTAL, DATA_VENDA, FORMA_PAGAMENTO, ORIGEM_VENDA)
VALUES 
(2, 102, 202, 'RPG', 2, 50.00, 100.00, '2025-02-05', 'PIX', 'E-commerce');

